# 默认配置（测试环境）
name = "polyflow-f-t"
compatibility_date = "2024-12-01"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# ========== 生产环境 ==========
[env.production]
name = "polyflow-f"
